CREATE TABLE [Order_Item](
    ORDER_ID UNIQUEIDENTIFIER NOT NULL,
    ITEM_ID UNIQUEIDENTIFIER NOT NULL,
    QUANTITY INT NOT NULL,
    PRIMARY KEY (ITEM_ID, ORDER_ID),
    FOREIGN KEY (ORDER_ID)
        REFERENCES [Order] (ID),
    FOREIGN KEY (ITEM_ID)
        REFERENCES [Item] (ID) 
);